name: discord_bot
description: Discord Bot
version: 1.0.0
homepage: https://github.com/ArcaneArts/discord_bot
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
dev_dependencies:
  build_runner: ^2.3.3
